### ISSUE TITLE
Ask root password when run pinata-ssh-forward

### ISSUE THREAD

**Issue by ozbillwang** [avsm/docker-ssh-agent-forward#14]
Anyone knows this issue?
```
root # $ pinata-ssh-forward
root@0.0.0.0's password:
```

**Comment by BlinkyStitt** [comment]
Sounds like your ssh-agent didn't work right.

What does `ssh-add -L` say? Make sure that shows you your public keys.

You might also want to try my fork which has several improvements and bug fixes: github.com/uber-common/docker-ssh-agent-forward
