### ISSUE TITLE
tini isn't needed anymore 

### ISSUE THREAD

**Issue by BlinkyStitt** [avsm/docker-ssh-agent-forward#3]
Docker 1.12+ handles an init process now

**Comment by mariusgrigaitis** [comment]
Also it does not currently work because of tini

```
$ pinata-ssh-forward
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/usr/bin/tini\": stat /usr/bin/tini: no such file or directory".
```

New location of tini is `/sbin/tini`, looks like fixed in #7

**Comment by ozbillwang** [comment]
@WyseNynja 

Could you please explain how Docker 1.12+ handles an init process, any relate document about it?

My docker version is 1.12.5, but `init` doesn't work with it. 

@mariusgrigaitis 

Can't make it work with /sbin/tini, `tini` can't be found (AWS Linux AMI)

**Comment by BlinkyStitt** [comment]
> Could you please explain how Docker 1.12+ handles an init process, any relate document about it?

https://github.com/docker/docker/blob/master/CHANGELOG.md#runtime-2
> Add boolean flag --init on dockerd and on docker run to use tini a zombie-reaping init process as PID 1 #26061 #28037

https://github.com/docker/docker/pull/28037
https://github.com/docker/docker/pull/26061

I actually ended up putting tini back into the image so that we wouldn't have to worry about someone forgetting this flag.

https://github.com/uber-common/docker-ssh-agent-forward/commit/494b72d3f946380c760cf6c8bce629be4b9dbb65
